development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: househunter
  pool: 5
  username: hh
  password: P@ssw0rd123
  host: 209.141.58.142
  port: 3306
 
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: househunter
  pool: 5
  username: hh
  password: P@ssw0rd123
  host: 209.141.58.142
  port: 3306

  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: househunter
  pool: 5
  username: hh
  password: P@ssw0rd123
  host: 209.141.58.142
  port: 3306

