development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: househunter
  pool: 5
  username: hh
  password: P@ssw0rd123
 
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: househunter
  pool: 5
  username: hh
  password: P@ssw0rd123
  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: househunter
  pool: 5
  username: hh
  password: P@ssw0rd123
