# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220ccb183efd8308d7fd39b88cf3b93bc061fef4557f709e0e22c8e87b99ea2b45e099a0d6387af52859d2a4da7c616e88c4bb40d2e3c2cd294f8fa85c49a70b

test:
  secret_key_base: 5c99eeaaff76445c1ddeda84754858d155af5240c97ba37d0c7b1133eafeda77af0a0632b23a3d25632bb9121f03c11fe91a5b932aabcf8d68cefac97d8b7fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
